### ISSUE TITLE
ExincrbyParams 希望可以增加KEEPTTL的设置

### ISSUE THREAD

**Issue by gooking** [alibaba/alibabacloud-tairjedis-sdk#16]
https://help.aliyun.com/document_detail/147113.html

例如这个应用场景，就需要用到 KEEPTTL，但是目前 SDK 应用中，没有办法去设置这个，希望可以增加

**Comment by yangbodong22011** [comment]
closed by https://github.com/alibaba/alibabacloud-tairjedis-sdk/commit/d6a1568ba6c844ab5ecb2f5eb26086327d93ec8f
