### ISSUE TITLE
maven依赖不能下载

### ISSUE THREAD

**Issue by yuyongkratos** [alibaba/alibabacloud-tairjedis-sdk#7]
<dependency>
  <groupId>com.aliyun.tair</groupId>
  <artifactId>alibabacloud-tairjedis-sdk</artifactId>
  <version>1.9.0</version>
</dependency>
无法下载这个依赖，maven找不到这个依赖。

**Comment by yangbodong22011** [comment]
@yuyongkratos Try this: https://mvnrepository.com/artifact/com.aliyun.tair/alibabacloud-tairjedis-sdk/1.9.0
```
<!-- https://mvnrepository.com/artifact/com.aliyun.tair/alibabacloud-tairjedis-sdk -->
<dependency>
    <groupId>com.aliyun.tair</groupId>
    <artifactId>alibabacloud-tairjedis-sdk</artifactId>
    <version>1.9.0</version>
</dependency>
```

**Comment by yangbodong22011** [comment]
Closed due to no reply for a long time
